title: Jake's Portfolio
iconURL: assets/gear-clipart-green-5.png
remote_theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: JacobHancock75
  github: jhancock75

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
